extern crate alloc;

use serde::{Deserialize, Serialize};

/// Keyboard input event generated by the keyboard V-Node.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub struct KeyEvent {
    /// Raw Set-1 scan code as delivered by IRQ1 handler.
    pub scancode: u8,
    /// ASCII translation for printable keys, when available.
    pub ascii: Option<u8>,
}

impl KeyEvent {
    #[must_use]
    pub const fn new(scancode: u8, ascii: Option<u8>) -> Self {
        Self { scancode, ascii }
    }
}
