extern crate alloc;

#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

/// Maximum number of bytes used by the IRQ-safe fixed ABI encoding.
pub const KEY_EVENT_FIXED_PAYLOAD_MAX_LEN: usize = 3;

/// Number of bytes in a fixed ABI payload without an ASCII byte.
pub const KEY_EVENT_FIXED_PAYLOAD_MIN_LEN: usize = 2;

const KEY_EVENT_ASCII_PRESENT: u8 = 0x01;

/// Keyboard input event generated by the keyboard V-Node.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct KeyEvent {
    /// Raw Set-1 scan code as delivered by IRQ1 handler.
    pub scancode: u8,
    /// ASCII translation for printable keys, when available.
    pub ascii: Option<u8>,
}

impl KeyEvent {
    #[must_use]
    pub const fn new(scancode: u8, ascii: Option<u8>) -> Self {
        Self { scancode, ascii }
    }

    /// Encodes this event into the fixed keyboard IRQ payload ABI.
    ///
    /// The ABI is intentionally tiny and allocation-free so interrupt handlers can
    /// place it on the stack before injecting the hardware event into IPC:
    ///
    /// - byte 0: raw Set-1 scancode
    /// - byte 1: flags; bit 0 means byte 2 contains an ASCII translation
    /// - byte 2: ASCII translation, present only when the flag is set
    #[must_use]
    pub const fn to_fixed_payload(self) -> ([u8; KEY_EVENT_FIXED_PAYLOAD_MAX_LEN], usize) {
        match self.ascii {
            Some(ascii) => (
                [self.scancode, KEY_EVENT_ASCII_PRESENT, ascii],
                KEY_EVENT_FIXED_PAYLOAD_MAX_LEN,
            ),
            None => ([self.scancode, 0, 0], KEY_EVENT_FIXED_PAYLOAD_MIN_LEN),
        }
    }

    /// Decodes a fixed keyboard IRQ payload.
    #[must_use]
    pub const fn from_fixed_payload(payload: &[u8]) -> Option<Self> {
        if payload.len() < KEY_EVENT_FIXED_PAYLOAD_MIN_LEN {
            return None;
        }

        let scancode = payload[0];
        let flags = payload[1];
        if flags & !KEY_EVENT_ASCII_PRESENT != 0 {
            return None;
        }

        if flags & KEY_EVENT_ASCII_PRESENT != 0 {
            if payload.len() != KEY_EVENT_FIXED_PAYLOAD_MAX_LEN {
                return None;
            }
            Some(Self::new(scancode, Some(payload[2])))
        } else if payload.len() == KEY_EVENT_FIXED_PAYLOAD_MIN_LEN {
            Some(Self::new(scancode, None))
        } else {
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{KeyEvent, KEY_EVENT_FIXED_PAYLOAD_MAX_LEN, KEY_EVENT_FIXED_PAYLOAD_MIN_LEN};

    #[test]
    fn fixed_payload_round_trips_scancode_without_ascii() {
        let event = KeyEvent::new(0x1e, None);

        let (payload, len) = event.to_fixed_payload();

        assert_eq!(len, KEY_EVENT_FIXED_PAYLOAD_MIN_LEN);
        assert_eq!(&payload[..len], &[0x1e, 0]);
        assert_eq!(KeyEvent::from_fixed_payload(&payload[..len]), Some(event));
    }

    #[test]
    fn fixed_payload_round_trips_scancode_with_ascii() {
        let event = KeyEvent::new(0x1e, Some(b'a'));

        let (payload, len) = event.to_fixed_payload();

        assert_eq!(len, KEY_EVENT_FIXED_PAYLOAD_MAX_LEN);
        assert_eq!(&payload[..len], &[0x1e, 1, b'a']);
        assert_eq!(KeyEvent::from_fixed_payload(&payload[..len]), Some(event));
    }

    #[test]
    fn fixed_payload_rejects_invalid_shapes() {
        assert_eq!(KeyEvent::from_fixed_payload(&[]), None);
        assert_eq!(KeyEvent::from_fixed_payload(&[0x1e]), None);
        assert_eq!(KeyEvent::from_fixed_payload(&[0x1e, 0, 0]), None);
        assert_eq!(KeyEvent::from_fixed_payload(&[0x1e, 1]), None);
        assert_eq!(KeyEvent::from_fixed_payload(&[0x1e, 0x80]), None);
    }
}
