[package]
name = "display-compositor"
version = "0.1.0"
edition = "2021"

[dependencies]
alloc = { package = "alloc", version = "0.0.0", optional = true }
aetheros_common = { path = "../../../../common" }
serde = { version = "=1.0.227", default-features = false, features = ["derive", "alloc"] }
postcard = { version = "1.0.8", default-features = false, features = ["alloc"] }
linked_list_allocator = "0.10.5"

# The binary target for the V-Node itself
[[bin]]
name = "display-compositor"
path = "src/main.rs"

