[env]
RUST_TARGET_PATH = ".cargo"

[target.'cfg(all())']
rustflags = [
    "--check-cfg=cfg(doc_cfg)"
]

[alias]
build-host = "build -p common"
build-kernel = "build --release --target .cargo/aetheros-x86_64.json -p aetheros-kernel"
build-vnode-webview = "build --release --target .cargo/aetheros-x86_64.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -p webview"
build-vnode-display-compositor = "build --release --target .cargo/aetheros-x86_64.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -p display-compositor"
build-baremetal-all = "build --release --workspace --target .cargo/aetheros-x86_64.json"