[build]
target = "x86_64-aether_os"

[target.x86_64-aether_os]
runner = "bootimage runner"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[env]
RUST_TARGET_PATH = { value = ".", relative = true }
