[package]
name = "aetheros-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
alloc = { package = "alloc", version = "0.0.0", optional = true }
common = { package = "aetheros-common", path = "../../common" }
postcard = { version = "1.0.8", default-features = false, features = ["alloc"] }
serde = { version = "1.0.198", default-features = false, features = ["derive", "alloc"] }

linked_list_allocator = "0.10.5"
